spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  r2dbc:
    url: r2dbc:postgresql://193.149.190.120:5432/souliving
    username: postgres
    password: 402012Ehodas
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZW1vLXNlY3VyaXR5IiwiaWF0IjoxNzA1OTQxOTk0LCJleHAiOjE3MDU5NDM1OTR9.y4NXkiSAcSULeaZgRTdlHEY9qyfUWPasPbjtHW6YXnY
  issuer: demo-security
  expirationTime: 30m

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

simplejavamail:
  smtp:
    host: smtp.gmail.com
