spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  r2dbc:
    url: r2dbc:postgresql://193.149.190.120:5432/coliver
    username: postgres
    password: 402012Ehodas
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: soulflatmate
    password: ieaa nwew ytth apej
    test-connection: false # проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    sender: # отправитель письма (его почта и имя)
      email: soulflatmate@gmail.com
      text: no-reply

jwt:
  secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZW1vLXNlY3VyaXR5IiwiaWF0IjoxNzA1OTQxOTk0LCJleHAiOjE3MDU5NDM1OTR9.y4NXkiSAcSULeaZgRTdlHEY9qyfUWPasPbjtHW6YXnY
  issuer: demo-security
  expirationTime: 30m

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
